### PR TITLE
Network.h Headers

### PR DESCRIPTION
**Pull request by jai-bhardwaj**
Included the required headers and fixed some implementation of string that were not using std namespace.

### CODE REVIEW

**Comment by dimske-sys** [comment]
Thx for the work,  changes have been merged :muscle: :star:

**Comment by jai-bhardwaj** [comment]
I've some doubts.
I was unable to use CUDA on my m1 Mac so those libraries were not detected by my compiler any idea how can I use them?

**Comment by dimske-sys** [comment]
Unfortunately The M1 Macs use Apple's own ARM-based processors, which are not compatible with the CUDA libraries that are built for NVIDIA's x86-based processors. As a result, you cannot use CUDA on an M1 Mac. If you want to use CUDA, you will need to use a different machine that has an NVIDIA GPU and is running a compatible version of Windows or Linux. Additionally, you will need to install the appropriate CUDA drivers and toolkit for your GPU and operating system. See the setup.md for a general setup guide, do note that it is still in its unfancy since its in active development but in the feature I will add support to run it on a server from Vultr,AWS... that has a NVidia GPU

**Comment by jai-bhardwaj** [comment]
Thank you @dimske-sys.

**Pull request merged**
